### ISSUE TITLE
爬取抖音安装Node.js 后仍然报错

### ISSUE THREAD

**Issue by HuiyiWANG615** [NanmiCoder/CrawlerTutorial#19]
安装Node.js 后仍然报错，大佬，请问怎么解决呢
Traceback (most recent call last):
  File "/Users/sophiawang/Library/Mobile Documents/com~apple~CloudDocs/MediaCrawler-main/main.py", line 49, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/sophiawang/Library/Mobile Documents/com~apple~CloudDocs/MediaCrawler-main/main.py", line 40, in main
    await crawler.start()
  File "/Users/sophiawang/Library/Mobile Documents/com~apple~CloudDocs/MediaCrawler-main/media_platform/douyin/core.py", line 67, in start
    await self.search()
  File "/Users/sophiawang/Library/Mobile Documents/com~apple~CloudDocs/MediaCrawler-main/media_platform/douyin/core.py", line 93, in search
    posts_res = await self.dy_client.search_info_by_keyword(keyword=keyword,
  File "/Users/sophiawang/Library/Mobile Documents/com~apple~CloudDocs/MediaCrawler-main/media_platform/douyin/client.py", line 134, in search_info_by_keyword
    return await self.get("/aweme/v1/web/general/search/single/", params, headers=headers)
  File "/Users/sophiawang/Library/Mobile Documents/com~apple~CloudDocs/MediaCrawler-main/media_platform/douyin/client.py", line 80, in get
    await self.__process_req_params(params, headers)
  File "/Users/sophiawang/Library/Mobile Documents/com~apple~CloudDocs/MediaCrawler-main/media_platform/douyin/client.py", line 64, in __process_req_params
    x_bogus = douyin_js_obj.call('sign', query, headers["User-Agent"])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/execjs/_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/execjs/_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/execjs/_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/execjs/_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/execjs/_external_runtime.py", line 85, in _exec_
    output = self._exec_with_tempfile(source)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/execjs/_external_runtime.py", line 127, in _exec_with_tempfile
    self._fail_on_non_zero_status(ret, stdoutdata, stderrdata)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/execjs/_external_runtime.py", line 134, in _fail_on_non_zero_status
    raise ProcessExitedWithNonZeroStatus(status=status, stdout=stdoutdata, stderr=stderrdata)
execjs._exceptions.ProcessExitedWithNonZeroStatus: (1, '', 'The operation couldn’t be completed. Unable to locate a Java Runtime.\nPlease visit http://www.java.com for information on installing Java.\n\n')

**Comment by NanmiCoder** [comment]
issue提交错地方了
